import asyncio
from plane.endpoints.users import Users
from plane.endpoints.urls import URLs
from types import TracebackType
from typing import Optional

class Client:
    def __init__(self, token: str, loop: Optional[asyncio.AbstractEventLoop] = ...) -> None: ...
    async def __aenter__(self) -> Client: ...
    async def __aexit__(self, exc_type: Optional[type], exc_val: Optional[BaseException], exc_tb: Optional[TracebackType]) -> None: ...
    async def close(self) -> None: ...
    @property
    def users(self) -> Users: ...
    @property
    def urls(self) -> URLs: ...
