import asyncio
from typing import Any

class HTTPClient:
    def __init__(self, token: str, loop: asyncio.AbstractEventLoop) -> None: ...
    async def close(self) -> None: ...
    async def get(self, path: str) -> dict[Any, Any]: ...
