class Routes:
    @property
    def base(self) -> str: ...
    @property
    def users(self) -> Users: ...
    @property
    def urls(self) -> URLs: ...

class Users:
    def user(self, id: int) -> str: ...
    def pronouns(self, id: int) -> str: ...
    def bans(self, id: int) -> str: ...
    def whitelists(self, id: int) -> str: ...
    def reputation(self, id: int) -> str: ...

class URLs:
    def url(self, url: str) -> str: ...
