from ..http import HTTPClient
from ..routes import Routes
from typing import Any

class Users:
    def __init__(self, http: HTTPClient, routes: Routes) -> None: ...
    async def get_user(self, id: int) -> dict[Any, Any]: ...
    async def get_pronouns(self, id: int) -> dict[Any, Any]: ...
    async def get_bans(self, id: int) -> dict[Any, Any]: ...
    async def get_whitelists(self, id: int) -> dict[Any, Any]: ...
    async def get_reputation(self, id: int) -> dict[Any, Any]: ...
